const EColl2Constants = {
    //eColl2.0 URIs
    ECOLL2_RECEIPT_TRANADD_PATH: '/rcpt/tranadd',
    ECOLL2_TAX_INV_RECEIPT_TRANADD_PATH: '/taxrcpt/tranadd',
    ECOLL2_DEPARTMENT_RECEIPT_TRANADD_PATH: '/norcpt/tranadd',
    ECOLL2_ESB_RETRIEVE_URL: '/ecoll2/1.0/payment/retrieve',
    ECOLL2_ESB_ACK_URL: '/ecoll2/1.0/payment/ack',

    //ESB Message Status
    ESB_STATUS_OK: '00000',

    //Counter default number
    EVENT_PAYMENT_COUNTER: '100000',
    PAYMENT_COUNTER_STEP: 10000,

    //Schema enum
    PAYMENT_CONFIGURATION_NOT_VERIFIED: 'NOT VERIFIED',
    PAYMENT_CONFIGURATION_VERIFIED: 'VERIFIED',
    PAYMENT_RECEIPT_ECOLL2_TAX_INV_RECEIPT: 'eColl2.0 Tax Invoice/Receipt',
    PAYMENT_RECEIPT_ECOLL2_RECEIPT: 'eColl2.0 Receipt',
    PAYMENT_RECEIPT_DEPARTMENT_RECEIPT: 'Department Receipt',
    PAYMENT_FAILURE: 'PAYMENT_FAILURE',
    PAYMENT_PROCESS_SUCCESS: 'PAYMENT_PROCESS_SUCCESS',
    PAYMENT_PROCESS_FAILED: 'PAYMENT_PROCESS_FAILED',
    PAYMENT_CONFIGURATION_EVENT_CODE_FIELD: 'Event Code',
    PAYMENT_CONFIGURATION_EVENT_NAME_FIELD: 'Event Name',
    PAYMENT_CONFIGURATION_EVENT_DATE_FIELD: 'Event Date',
    PAYMENT_CONFIGURATION_EVENT_ADDITONAL_FIELD: "Event Additional Form Field"
  };
  
  export default EColl2Constants;